apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: ${project.artifactId}-configmap
data:
  application.properties: |-
    amqphub.amqp10jms.remote-url=amqp://broker-amq-headless:61616
    spring.datasource.url=jdbc:mysql://mysql:3306/example?autoReconnect=true&useSSL=false
