apiVersion: v1
kind: Service
metadata:
  name: broker-amq-headless
  labels:
    app: broker-amq
spec:
  ports:
  - port: 61616
    name: artemis
  - port: 61617
    name: artemis-ssl
  clusterIP: None
  selector:
    app: broker-amq