apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
  labels:
    application: broker
  name: broker-amq
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  selector:
    matchLabels:
      app: broker-amq
  serviceName: broker-amq-headless
  template:
    metadata:
      labels:
        app: broker-amq
        application: broker
      name: broker-amq
    spec:
      containers:
        - env:
            - name: BROKER_XML
              valueFrom:
                configMapKeyRef:
                  key: broker.xml
                  name: broker-amq-configmap
            - name: AMQ_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: broker-amq-secret
            - name: AMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: broker-amq-secret
            - name: AMQ_CLUSTER_USER
              valueFrom:
                secretKeyRef:
                  key: cluster-username
                  name: broker-amq-secret
            - name: AMQ_CLUSTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: cluster-password
                  name: broker-amq-secret
            - name: AMQ_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: truststore-password
                  name: broker-amq-secret
            - name: AMQ_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keystore-password
                  name: broker-amq-secret
            - name: AMQ_REQUIRE_LOGIN
              value: "true"
            - name: JAVA_OPTS
              value: "-Damq.truststore.password=$AMQ_TRUSTSTORE_PASSWORD -Damq.keystore.password=$AMQ_KEYSTORE_PASSWORD -Damq.user=$AMQ_USER -Damq.password=$AMQ_PASSWORD -Damq.cluster.user=$AMQ_CLUSTER_USER -Damq.cluster.password=$AMQ_CLUSTER_PASSWORD"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: "172.30.1.1:5000/dc2/custom-amq7:latest"
          imagePullPolicy: IfNotPresent
          name: broker-amq
          ports:
            - containerPort: 8161
              name: console-jolokia
              protocol: TCP
            - containerPort: 61616
              name: all
              protocol: TCP
            - containerPort: 61617
              name: all-ssl
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/amq/bin/readinessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/amq/data
              name: broker-amq-pvol
            - mountPath: /etc/amq-secret-volume
              name: broker-secret-volume
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: broker-secret-volume
          secret:
            defaultMode: 420
            secretName: broker-amq-secret
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: broker-amq-pvol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
